version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    ports:
      - "5432:5432"
  app:
    image: my-node-app
    ports:
      - 13000:3000
    volumes:
      - .:/app # Mount current directory to /app in the container
      - /app/node_modules # Ignore node_modules (prevents overwriting container-installed modules)
    command: ["npm", "run", "dev"] # Ensure your dev script watches for file changes